# Generated by Django 5.1.1 on 2026-02-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_comment_count_alter_post_image_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
